### ISSUE TITLE
Extension breaks with paths that contain parentheses on Mac

### ISSUE THREAD

**Issue by SiddharthParatkar** [CalLavicka/c0-vscode-extension#40] opened 2020-02-23 21:35 UTC
When opening a file which relies on another file in a directory with parentheses in its path, the file fails to parse.

**Comment by ishantheperson** [comment] 2020-02-24 16:22
I think it's something to do with this line

https://github.com/CalLavicka/c0-vscode-extension/blob/d9786629474d35589379c1c3ff22cc19e5371f4f/server/src/parse.ts#L295

We need to be able to handle arbitrary URL encoded sequences

**Comment by ishantheperson** [comment] 2020-02-27 06:13
This seems useful https://github.com/microsoft/vscode/blob/master/src/vs/base/common/uri.ts

**Comment by ishantheperson** [comment] 2020-02-27 17:39
The problem is that in the cache, we sometimes add the URI-encoded version of the path and sometimes add the regular string. This inconsistency can cause a file to be loaded twice, which can then cause compilation to mysteriously fail

**Comment by ishantheperson** [comment] 2020-03-18 18:05
Should be fixed now, need to test on windows

**Comment by ishantheperson** [comment] 2020-03-19 00:09
Fixed on both windows/mac

**Closed by ishantheperson** 2020-03-19 00:09 UTC
Labels: bug
